# Generated by Django 3.0.5 on 2020-04-12 05:16

import creditcards.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cards_info',
            fields=[
                ('card_info_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_on_card', models.CharField(max_length=50)),
                ('cc_number', creditcards.models.CardNumberField(help_text='card number', max_length=25)),
                ('cc_expiry', creditcards.models.CardExpiryField(help_text='expiration date')),
                ('cc_code', creditcards.models.SecurityCodeField(help_text='security code', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('line1', models.CharField(max_length=150)),
                ('line2', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField(max_length=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('contact', phone_field.models.PhoneField(help_text='Contact phone number', max_length=50)),
                ('Gender', models.CharField(choices=[('ML', 'Male'), ('FM', 'Female'), ('OT', 'Others')], max_length=2)),
                ('dob', models.DateField(max_length=8)),
                ('role', models.CharField(choices=[('CST', 'Customer'), ('ADM', 'Admin'), ('DRV', 'Driver'), ('OPR', 'Operator'), ('ATD', 'Attendant'), ('CLN', 'Cleaner'), ('RBA', 'Rbackadmin')], max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='rest_stop_contact',
            fields=[
                ('rest_stop_contact_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_roles.user')),
            ],
        ),
        migrations.CreateModel(
            name='operator',
            fields=[
                ('operator_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=30)),
                ('gst_no', models.CharField(max_length=20)),
                ('owner_details_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_roles.user')),
            ],
        ),
        migrations.CreateModel(
            name='driver',
            fields=[
                ('qualification', models.CharField(choices=[('BELOW 10TH', 'BELOW 10TH'), ('10TH PASS', '10TH PASS'), ('12TH PASS', '12TH PASS'), ('GRADUATE', 'GRADUATE'), ('POST GRADUATE', 'POST GRADUATE')], max_length=30)),
                ('languages', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Kannada', 'Kannada'), ('Malayalam', 'Malayalam'), ('Marathi', 'Marathi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Urdu', 'Urdu'), ('Gujarati', 'Gujarati'), ('Bengali', 'Bengali')], help_text='You can select multiple languages', max_length=50)),
                ('joindate_wrtoperator', models.DateField(blank=True, help_text='Enter Joining date with operator')),
                ('driver_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lisence_no', models.IntegerField(max_length=20)),
                ('lisence_expiry_date', models.DateField()),
                ('driver_salary', models.FloatField(max_length=7)),
                ('current_operator_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_roles.operator')),
                ('driver_details_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_roles.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_refferal_code', models.CharField(blank=True, max_length=25)),
                ('referred_by', models.CharField(blank=True, max_length=25)),
                ('referred_method', models.CharField(blank=True, choices=[('WA', 'Whatsapp'), ('MA', 'Mobile App'), ('WB', 'Web')], max_length=2)),
                ('sign_up_method', models.CharField(blank=True, choices=[('LN', 'Linkedin'), ('GM', 'Gmail'), ('FB', 'Facebook'), ('AP', 'Apple Id')], max_length=2)),
                ('payment_method', models.CharField(blank=True, choices=[('PTM', 'Paytm'), ('UPI', 'Upi'), ('CRD', 'Card'), ('CSH', 'Cash'), ('NBG', 'Netbanking')], max_length=3)),
                ('medical_history', models.CharField(blank=True, max_length=50)),
                ('blood_group', models.CharField(max_length=3)),
                ('cards_list', models.ManyToManyField(to='user_roles.cards_info')),
                ('customer_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_roles.user')),
            ],
        ),
        migrations.CreateModel(
            name='cleaner',
            fields=[
                ('qualification', models.CharField(choices=[('BELOW 10TH', 'BELOW 10TH'), ('10TH PASS', '10TH PASS'), ('12TH PASS', '12TH PASS'), ('GRADUATE', 'GRADUATE'), ('POST GRADUATE', 'POST GRADUATE')], max_length=30)),
                ('languages', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Kannada', 'Kannada'), ('Malayalam', 'Malayalam'), ('Marathi', 'Marathi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Urdu', 'Urdu'), ('Gujarati', 'Gujarati'), ('Bengali', 'Bengali')], help_text='You can select multiple languages', max_length=50)),
                ('joindate_wrtoperator', models.DateField(blank=True, help_text='Enter Joining date with operator')),
                ('cleaner_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cleaner_salary', models.FloatField(max_length=7)),
                ('cleaner_details_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_roles.user')),
                ('current_operator_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_roles.operator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='bankinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=40)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_no', models.IntegerField(max_length=30)),
                ('ifsc', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_roles.user')),
            ],
        ),
        migrations.CreateModel(
            name='attendant',
            fields=[
                ('qualification', models.CharField(choices=[('BELOW 10TH', 'BELOW 10TH'), ('10TH PASS', '10TH PASS'), ('12TH PASS', '12TH PASS'), ('GRADUATE', 'GRADUATE'), ('POST GRADUATE', 'POST GRADUATE')], max_length=30)),
                ('languages', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Kannada', 'Kannada'), ('Malayalam', 'Malayalam'), ('Marathi', 'Marathi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Urdu', 'Urdu'), ('Gujarati', 'Gujarati'), ('Bengali', 'Bengali')], help_text='You can select multiple languages', max_length=50)),
                ('joindate_wrtoperator', models.DateField(blank=True, help_text='Enter Joining date with operator')),
                ('attendant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendant_salary', models.FloatField(max_length=7)),
                ('attendant_details_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_roles.user')),
                ('current_operator_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_roles.operator')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
