# Generated by Django 3.0.5 on 2020-04-12 05:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='voucher',
            fields=[
                ('voucher_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher_code', models.CharField(max_length=50)),
                ('voucher_discount', models.FloatField()),
                ('max_discount', models.IntegerField(max_length=6)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
            ],
        ),
    ]
