# Generated by Django 3.0.5 on 2020-04-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeschedulemodel',
            name='route_group',
            field=models.UUIDField(),
        ),
    ]
