# Generated by Django 3.0.5 on 2020-04-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200422_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busconfigmodel',
            name='bus_seat_layout',
        ),
    ]
