# Generated by Django 3.0.5 on 2020-04-22 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_busconfigmodel_bus_seat_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('search_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_group_id', models.UUIDField()),
                ('route_group', models.CharField(max_length=50)),
                ('from_source', models.CharField(max_length=50)),
                ('to_dest', models.CharField(max_length=50)),
                ('bus_config', models.CharField(max_length=50)),
                ('dep_date', models.DateField()),
                ('arr_date', models.DateField()),
                ('dep_time', models.TimeField()),
                ('arr_time', models.TimeField()),
                ('from_order', models.IntegerField()),
                ('to_order', models.IntegerField()),
            ],
        ),
    ]
